# Workflow-ржПрж░ ржирж╛ржо
name: Daily Device Scrape at 8:59 PM BDT

on:
  # рзз. ржирж┐рж░рзНржжрж┐рж╖рзНржЯ рж╕ржорзЯрзЗ рж╕рзНржмрзЯржВржХрзНрж░рж┐рзЯржнрж╛ржмрзЗ ржЪрж╛рж▓рж╛ржирзЛрж░ ржЬржирзНржп рж╕рж┐ржбрж┐ржЙрж▓
  schedule:
    # cron ржлрж░ржорзНржпрж╛ржЯ: ржорж┐ржирж┐ржЯ ржШржгрзНржЯрж╛ ржжрж┐ржи ржорж╛рж╕ рж╕ржкрзНрждрж╛рж╣рзЗрж░-ржжрж┐ржи
    # 14:59 UTC рж╣рж▓рзЛ 8:59 PM BDT (UTC+6)
    - cron: '59 14 * * *'

  # рзи. GitHub-ржПрж░ Actions ржЯрзНржпрж╛ржм ржерзЗржХрзЗ ржорзНржпрж╛ржирзБрзЯрж╛рж▓рж┐ ржЪрж╛рж▓рж╛ржирзЛрж░ рж╕рзБржмрж┐ржзрж╛
  workflow_dispatch:

# ржПржЗ Job-ржХрзЗ рж░рж┐ржкрзЛржЬрж┐ржЯрж░рж┐рждрзЗ ржлрж╛ржЗрж▓ рж▓рзЗржЦрж╛рж░ (contents: write) ржЕржирзБржорждрж┐ ржжрзЗржУрзЯрж╛ рж╣ржЪрзНржЫрзЗ
# ржПржЯрж┐ ржбрзЗржЯрж╛ ржлрж╛ржЗрж▓ (CSV, JSON, ржЗрждрзНржпрж╛ржжрж┐) рж╕рзЗржн ржХрж░рж╛рж░ ржЬржирзНржп ржЕржкрж░рж┐рж╣рж╛рж░рзНржп
permissions:
  contents: write

jobs:
  # Job-ржПрж░ ржирж╛ржо
  run-scraper:
    # ржХрзЛржи ржЕржкрж╛рж░рзЗржЯрж┐ржВ рж╕рж┐рж╕рзНржЯрзЗржорзЗ ржЪрж▓ржмрзЗ (рж╕рж░рзНржмрж╢рзЗрж╖ Ubuntu)
    runs-on: ubuntu-latest

    steps:
      # ржзрж╛ржк рзз: ржЖржкржирж╛рж░ рж░рж┐ржкрзЛржЬрж┐ржЯрж░рж┐рж░ ржХрзЛржб ржбрж╛ржЙржирж▓рзЛржб ржХрж░рж╛
      - name: Checkout repository
        uses: actions/checkout@v4

      # ржзрж╛ржк рзи: Python 3.11 рж╕рзЗржЯржЖржк ржХрж░рж╛
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          # pip ржкрзНржпрж╛ржХрзЗржЬ ржХрзНржпрж╛рж╢ ржХрж░рзЗ рж░рж╛ржи ржжрзНрж░рзБржд ржХрж░рж╛рж░ ржЬржирзНржп
          cache: 'pip'

      # ржзрж╛ржк рзй: ржмржЯ ржЪрж╛рж▓рж╛ржирзЛрж░ ржЬржирзНржп ржкрзНрж░рзЯрзЛржЬржирзАрзЯ рж╕ржм рж▓рж╛ржЗржмрзНрж░рзЗрж░рж┐ ржЗржирж╕рзНржЯрж▓ ржХрж░рж╛
      - name: Install all dependencies
        run: |
          python -m pip install --upgrade pip
          # ржЖржкржирж╛рж░ main.py ржЪрж╛рж▓рж╛ржирзЛрж░ ржЬржирзНржп ржкрзНрж░рзЯрзЛржЬржирзАрзЯ рж╕ржм рж▓рж╛ржЗржмрзНрж░рзЗрж░рж┐ ржПржЦрж╛ржирзЗ ржпрзЛржЧ ржХрж░рзБржи
          pip install requests Pillow playwright
          # Playwright-ржПрж░ ржЬржирзНржп ржмрзНрж░рж╛ржЙржЬрж╛рж░ ржПржмржВ рж╕рж┐рж╕рзНржЯрзЗржо рж▓рж╛ржЗржмрзНрж░рзЗрж░рж┐ ржЗржирж╕рзНржЯрж▓ ржХрж░рж╛
          python -m playwright install --with-deps chromium

      # ржзрж╛ржк рзк: ржЖржкржирж╛рж░ ржкрж╛ржЗржержи рж╕рзНржХрзНрж░рж┐ржкрзНржЯржЯрж┐ ржЪрж╛рж▓рж╛ржирзЛ
      - name: Run Python Scraper Script
        env:
          # GitHub Secret ржерзЗржХрзЗ ржЖржкржирж╛рж░ ржЯрзЗрж▓рж┐ржЧрзНрж░рж╛ржо ржЯрзЛржХрзЗржи ржПржЦрж╛ржирзЗ ржпрзБржХрзНржд ржХрж░рж╛ рж╣ржЪрзНржЫрзЗ
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        # -u ржлрзНрж▓рзНржпрж╛ржЧ ржмрзНржпржмрж╣рж╛рж░ ржХрж░рж╛ рж╣рзЯрзЗржЫрзЗ ржпрж╛рждрзЗ рж▓ржЧржЧрзБрж▓рзЛ рж░рж┐рзЯрзЗрж▓-ржЯрж╛ржЗржорзЗ ржжрзЗржЦрж╛ ржпрж╛рзЯ
        run: python -u main.py

      # ржзрж╛ржк рзл: рж╕рзНржХрзНрж░рж┐ржкрзНржЯ ржЪрж▓рж╛рж░ ржкрж░ ржкрж░рж┐ржмрж░рзНрждрж┐ржд ржлрж╛ржЗрж▓ржЧрзБрж▓рзЛ ржХржорж┐ржЯ ржПржмржВ ржкрзБрж╢ ржХрж░рж╛
      - name: Commit and push data files
        run: |
          # Git-ржПрж░ ржЬржирзНржп ржЗржЙржЬрж╛рж░ ржХржиржлрж┐ржЧрж╛рж░ ржХрж░рж╛
          git config user.name 'github-actions[bot]'
          git config user.email 'github-actions[bot]@users.noreply.github.com'
          
          # рж░рж┐ржкрзЛржЬрж┐ржЯрж░рж┐рж░ рж╕ржм ржкрж░рж┐ржмрж░рзНрждрж┐ржд ржлрж╛ржЗрж▓ (scraped_devices.csv, *.json, images/*) ржпрзЛржЧ ржХрж░рж╛
          git add -A
          
          # ржпржжрж┐ ржХрзЛржирзЛ ржлрж╛ржЗрж▓рзЗ ржЖрж╕рж▓рзЗржЗ ржкрж░рж┐ржмрж░рзНрждржи рж╣рзЯрзЗ ржерж╛ржХрзЗ, рждржмрзЗржЗ ржПржХржЯрж┐ ржирждрзБржи ржХржорж┐ржЯ рждрзИрж░рж┐ ржХрж░рзЗ ржкрзБрж╢ ржХрж░ржмрзЗ
          # ржЕржирзНржпржерж╛рзЯ, ржХрзЛржирзЛ ржХржорж┐ржЯ рж╣ржмрзЗ ржирж╛
          if ! git diff --staged --quiet; then
            git commit -m "CHORE: Auto-update scraped device data"
            git push
            echo "тЬЕ Data files have been updated and pushed to the repository."
          else
            echo "ЁЯСН No changes in data files to commit."
          fi

